"""Updated OAuthTable

Revision ID: 5c775265bd74
Revises: 807c6fc14662
Create Date: 2024-09-21 16:42:01.670424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c775265bd74'
down_revision: Union[str, None] = '807c6fc14662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_tokens', sa.Column('id_token', sa.Text(), nullable=True))
    op.add_column('oauth_tokens', sa.Column('expires_at', sa.Integer(), nullable=True))
    op.add_column('oauth_tokens', sa.Column('token_type', sa.String(), nullable=True))
    op.add_column('oauth_tokens', sa.Column('sub', sa.String(), nullable=True))
    op.add_column('oauth_tokens', sa.Column('exp', sa.Integer(), nullable=True))
    op.add_column('oauth_tokens', sa.Column('iat', sa.Integer(), nullable=True))
    op.add_column('oauth_tokens', sa.Column('iss', sa.String(), nullable=True))
    op.add_column('oauth_tokens', sa.Column('nonce', sa.String(), nullable=True))
    op.drop_column('oauth_tokens', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_tokens', sa.Column('refresh_token', sa.TEXT(), nullable=True))
    op.drop_column('oauth_tokens', 'nonce')
    op.drop_column('oauth_tokens', 'iss')
    op.drop_column('oauth_tokens', 'iat')
    op.drop_column('oauth_tokens', 'exp')
    op.drop_column('oauth_tokens', 'sub')
    op.drop_column('oauth_tokens', 'token_type')
    op.drop_column('oauth_tokens', 'expires_at')
    op.drop_column('oauth_tokens', 'id_token')
    # ### end Alembic commands ###
